%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/silvers/data/RCEMIP/tables/Table_A2_RCE_large305.txt
%
% Auto-generated by MATLAB on 27-Oct-2020 14:53:38

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "Model", "F_NET", "R_TOA", "Q_OCN", "R_NET", "OLR", "ASR_TOA", "LHF", "SHF", "PW", "Precip", "LWP", "IWP", "clwvi_avg", "LapseRate"];
opts.VariableTypes = ["double", "string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["VarName2", "Model"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["VarName2", "Model"], "EmptyFieldRule", "auto");

% Import the data
TableA2RCElarge305 = readtable("/Users/silvers/data/RCEMIP/tables/Table_A2_RCE_large305.txt", opts);

%% Convert to output type
TableA2RCElarge305 = table2cell(TableA2RCElarge305);
numIdx = cellfun(@(x) ~isnan(str2double(x)), TableA2RCElarge305);
TableA2RCElarge305(numIdx) = cellfun(@(x) {str2double(x)}, TableA2RCElarge305(numIdx));

%% Clear temporary variables
clear opts
